python validate_loop.py --model claude-haiku-4.5-reasoning
python validate_loop.py --model claude-haiku-4.5
python validate_loop.py --model cwm
python validate_loop.py --model cwm-pretrain
python validate_loop.py --model deepseek-v3.2-reasoning
python validate_loop.py --model deepseek-v3.2
python validate_loop.py --model gemini-3-pro-preview-reasoning
python validate_loop.py --model gemini-3-pro-preview
python validate_loop.py --model gpt-5-mini-reasoning
python validate_loop.py --model gpt-5-mini